### ISSUE TITLE
[iOS] Sobriety - Motion Sensor Update Rate (ESOB003)

### ISSUE THREAD

**Issue by Pierre-CGI** [green-code-initiative/ecoCode-android#44]
Using the Core Motion API, your app can receive continuous motion updates in the form of accelerometer, gyroscope, and device motion (rotation, acceleration, and more) events. Yet you don't often need these updates as soon as they are generated. Before registering to receive these recurring motion updates, you can specify an interval that meets your app’s needs, using `CMMotionManager#accelerometerUpdateInterval`, `CMMotionManager#gyroUpdateInterval`, `CMMotionManager#deviceMotionUpdateInterval` and `CMMotionManager#magnetometerUpdateInterval` properties. The larger the interval, the fewer events are delivered to your app, improving battery life.

**Comment by zippy1978** [comment]
Addressed by https://github.com/green-code-initiative/ecoCode-mobile/pull/59
