### ISSUE TITLE
Upgrade licences (and system)

### ISSUE THREAD

**Issue by dedece35** [green-code-initiative/ecoCode-android#63]
iOS plugin was created recently and thus, the licence managment and information are differents from android and codeNarc projects.

think about licencing system with team and apply it to standard plugin also.
(@glalloue @utarwyn @olegoaer @jhertout @zippy1978 @jduigoudev )

check PR #62 with example for iOS part

maven plugin to update all files : https://mycila.carbou.me/license-maven-plugin/
`maven licence:format` command to generate or update headers in files

What I noticed : 
- what kind of licence : 
   - `GPL v3` on parent `pom.xml` file
   - `GNU LGPL 3` on iOS `pom.xml` file
   - ==> to put on parent part ?
- `inceptionYear` used in generated headers for licence : 
   - iOS part : `2022` ==> why not 2023, or from 2020 to 2023 ?
   - android part : `2020`
   - codeNarc part : no inceptionYear => to add
   - ==> to put on parent part ?
- `organization` information used on licence system is present on parent `pom.xml` file
- one `LICENSE.txt` file and one `NOTICE.txt` file on each submodule and with content different

Why not put all these information on parent `pom.xml` file and manage licencing from here ?

**Comment by jhertout** [comment]
I updated the license management system to use https://mycila.carbou.me/license-maven-plugin/ as in iOS plugin except for the CodeNarc part which has its own license. For me all is ok now.
