### ISSUE TITLE
check compatibility with SonarQube 10.0.0 (manual checks)

### ISSUE THREAD

**Issue by dedece35** [green-code-initiative/ecoCode-android#66]
Hi @zippy1978, @jhertout, @jduigoudev,

like `ecocode` plugin with issue #189, could you check that all is ok with android and ios plugins with SonarQube 10.0.0 on laste release version of plugins, please ?

thank you

(plop @glalloue, @olegoaer)

**Comment by zippy1978** [comment]
Hi @dedece35 

I did the checks on iOS (from here https://github.com/green-code-initiative/ecoCode-ios) with the test projet: every is ok !

Just to be sure: should we update SQ version to 10.0 or stay on the LTS ? (I think staying on the LTS is better)

**Comment by dedece35** [comment]
Hi @zippy1978, ok cool !
Good question ... as I see in DockerFile, the version is `9.9-community` thus the LTS as mentionned in the official Docker repository : https://hub.docker.com/_/sonarqube/#!
Personnaly, I made the modification to 10.0 in standard ecocode plugins.
I think if all is OK and there is an official new release of SonarQube, as well, do it ... even if it is'nt the LTS version yet.

What do you think about it @julien-hertout-neomades ?

**Comment by jhertout** [comment]
Hello,

We will change the SonarQube version to 10 in the docker configuration in the Android project. This is just a version to test, and I think it is important to show it works in the latest version.
For users of older SonarQube, we have the "Plugins version compatibility" array in the Readme. I think it is enough.

**Comment by jhertout** [comment]
The SonarQube version 10 is now the one use in the docker file. All is OK and since the plugin was validated by SonarSource : https://community.sonarsource.com/t/new-plugin-ecocode-android-requesting-inclusion-in-sonarqube-marketplace/104674 I will close this issue.
