### ISSUE TITLE
Improve rule EC5002 (SDK range) description

### ISSUE THREAD

**Issue by jhertout** [green-code-initiative/ecoCode-android#78]
As mentioned by Ann here: https://community.sonarsource.com/t/new-plugin-ecocode-android-requesting-inclusion-in-sonarqube-marketplace/104674/3 the description of this rule is not very clear : 

`When looking at the minSdkVersion and targetSdkVersion (or minSdk, targetSdk) attributes for the <uses-sdk> in the AndroidManifest.xml file, the amplitude of supported platform versions should not be too wide, at the risk of making the app too heavy to handle all cases.` -> "too heavy to handle all cases." is not very understandable.

We must clarify this rule. @olegoaer an idea?

**Comment by olegoaer** [comment]
I'm not a big fan of this rule any more, as it's still vague. I was planning to remove it from the catalogue.

**Comment by jhertout** [comment]
OK, in this case we can wait until we remove it. Do we create an issue to remove the rule and close this one?

**Comment by jhertout** [comment]
OK, I did not see that. I close this issue and add one to remove the rule.
