### ISSUE TITLE
Server unreachable

### ISSUE THREAD

**Issue by EduardoXav** [green-code-initiative/ecoCode-android#85]
**Describe the bug**
Server unreachable

**To Reproduce**
1. Set up sonarqube on kotlin
2. setup gradle.properties
3. Change configuratin to :app:sonarqube cause :(app):sonarqube doesn't work
4. Click play
5. error message : Status returned by url [https://sonarqube.ecocode.io/batch/index] is not valid: [503]

**Expected behavior**
Show website

![image](https://github.com/green-code-initiative/ecoCode-android/assets/93222151/c7594741-faaa-462c-8a7f-5a915b220ced)

**Comment by jhertout** [comment]
Hi,

we had some issues with our DNS last month. Do you always have the problem?

Thanks

**Comment by EduardoXav** [comment]
Hi,

no more problems on my side, everything works fine

Thank you
